# Generated by Django 4.2 on 2023-06-12 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_imagepost_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 19, 46, 0, 542606, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagePost',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
