# Generated by Django 4.2 on 2023-06-14 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_date_posted_alter_post_imagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 11, 49, 1, 297034, tzinfo=datetime.timezone.utc)),
        ),
    ]
